---
title: "FIFA Data Collection"
author: "Kyle Furlong"
date: "April 24, 2018"
output: html_document
---

```{r warning=FALSE, include=FALSE}
library(plyr)
library(dplyr)
library(XML)
library(xml2)
library(stringr)
library(rvest)
library(tidyr)
library(ggplot2)
library(knitr)
library(lubridate)
library(reshape)
library(reshape2)
as.numeric.factor <- function(x) {as.numeric(levels(x))[x]}
```

```{r cache=TRUE}
fifa <- read.csv("fifaElo.csv", header = FALSE)
```

```{r}
full.df <- c()
for(i in seq(2,nrow(fifa),by=16)){
  end.i <- i+15
  
  i.df <- data.frame(t(fifa[c(1,i:end.i),]))
  names(i.df) <- c("year", "rank", "country", "rating", "avg.rank", "avg.rating","year.change.rank", "year.change.rating", "total.games", "home", "away", "neutral", "wins", "losses", "draws", "goals.for", "goals.against")
  full.df <- rbind.data.frame(full.df, i.df)
}

fifa.df <- data.frame(full.df)
rownames(fifa.df) <- c()

fifa.df$year <- as.numeric.factor(fifa.df$year)
fifa.df$rank <- as.numeric.factor(fifa.df$rank)
fifa.df$rating <- as.numeric.factor(fifa.df$rating)
fifa.df$avg.rank <- as.numeric.factor(fifa.df$avg.rank)
fifa.df$avg.rating <- as.numeric.factor(fifa.df$avg.rating)

fifa.df$year.change.rank <- as.numeric(gsub(x = fifa.df$year.change.rank, pattern = "\\?", replacement = "\\-"))

fifa.df$year.change.rating <- as.numeric(gsub(x = fifa.df$year.change.rating, 
                                                   pattern = "\\?", replacement = "\\-"))
fifa.df$total.games <- as.numeric.factor(fifa.df$total.games)
fifa.df$home <- as.numeric.factor(fifa.df$home)
fifa.df$away <- as.numeric.factor(fifa.df$away)
fifa.df$neutral <- as.numeric.factor(fifa.df$neutral)
fifa.df$wins <- as.numeric.factor(fifa.df$wins)
fifa.df$losses <- as.numeric.factor(fifa.df$losses)
fifa.df$draws <- as.numeric.factor(fifa.df$draws)
fifa.df$goals.for <- as.numeric.factor(fifa.df$goals.for)
fifa.df$goals.against <- as.numeric.factor(fifa.df$goals.against)

fifa.df <- subset(fifa.df, !is.na(rank))
head(fifa.df, 20)
```

```{r}
ggplot(fifa.df, aes(x = year, y = (wins-losses), group = country)) + geom_line()

```

```{r}
library(triangle)
results <- read.csv("results.csv")
cap.dist <- read.csv("capdist.csv")[,c(2,4,5)]
cap.codes <- read.csv("countryCodes.csv")[,1:2]

fifa.df2 <- merge.data.frame(x = fifa.df, y = cap.codes, by = "country", all.x = TRUE, all.y = FALSE)
fifa.df2$code[fifa.df2$country == "West Germany" | fifa.df2$country == "East Germany"] <- "DEU"
fifa.df2$code[fifa.df2$country == "Soviet Union"] <- "RUS"
fifa.df2$code[fifa.df2$country == "Czechia"] <- "CZE"
fifa.df2$code[fifa.df2$country == "North Korea"] <- "PRK"
fifa.df2$code[fifa.df2$country == "South Korea"] <- "KOR"
fifa.df2$code[fifa.df2$country == "United States"] <- "USA"
fifa.df2$code[fifa.df2$country == "Gold Coast"] <- "CIV"
fifa.df2$code[fifa.df2$country == "Democratic Republic of Congo"] <- "COD"
fifa.df2$code[grepl(x = fifa.df2$country, pattern = "Vietnam")] <- "VNM"
fifa.df2$code[fifa.df2$country == "Bosnia and Herzegovina"] <- "BIH"
fifa.df2$code[grepl(x = fifa.df2$country, pattern = "Rhodesia")] <- "ZWE"
#fifa.df2$code[fifa.df2$country == "Northern Rhodesia"] <- "ZWE"
#fifa.df2$code[fifa.df2$country == "Southern Rhodesia"] <- "ZWE"
fifa.df2$code[fifa.df2$country == "French Congo"] <- "CON"
fifa.df2$code[fifa.df2$country == "Curaçao"] <- "CUW"
fifa.df2$code[fifa.df2$country == "Dahomey"] <- "BEN"
fifa.df2$code[fifa.df2$country == "Netherlands Antilles"] <- "ATG"
fifa.df2$code[fifa.df2$country == "Saint Vincent and the Grenadines"] <- "VCT"
fifa.df2$code[fifa.df2$country == "Northern Cyprus"] <- "CYP"
fifa.df2$code[fifa.df2$country == "Saint Lucia"] <- "LCA"
fifa.df2$code[fifa.df2$country == "Portuguese Guinea"] <- "GNQ"
fifa.df2$code[fifa.df2$country == "Réunion"] <- "REU"
fifa.df2$code[fifa.df2$country == "Saint Kitts"] <- "KNA"
fifa.df2$code[fifa.df2$country == "Saint Kitts and Nevis"] <- "KNA"
fifa.df2$code[fifa.df2$country == "Ruanda-Urundi"] <- "RWA"
fifa.df2$code[fifa.df2$country == "Zanzibar"] <- "TZA"
fifa.df2$code[fifa.df2$country == "São Tomé and Príncipe"] <- "STP"
fifa.df2$code[fifa.df2$country == "Sint Maarten"] <- "MAF"
fifa.df2$code[grepl(x = fifa.df2$country, pattern = "somosa")] <- "WSM"
fifa.df2$code[fifa.df2$country == "Turks and Caicos"] <- "TCA"
fifa.df2$code[fifa.df2$country == "US Virgin Islands"] <- "VGB"
fifa.df2$code[fifa.df2$country == "Saint Barthélemy"] <- "BLM"
fifa.df2$code[fifa.df2$country == "Federated States of Micronesia"] <- "FSM"

fifa.df2 <- subset(fifa.df2, !is.na(code))

top10 <- fifa.df2 %>%
  select(country, year, rank, code) %>%
  filter(rank<=10) 
top10
```


```{r maybe none of this actually, eval = FALSE}

games <- subset(results, tournament == "FIFA World Cup qualification") %>%
  mutate(year = year(date)) %>%
  filter(year > 1949) %>%
  select(1:5,9) %>%
  merge(y = cap.codes, by.x = "home_team", by.y = "country", all.x = TRUE, all.y = FALSE) %>%
  select(1:6, home.code=7) %>%
  merge(y = cap.codes, by.x = "away_team", by.y = "country", all.x = TRUE, all.y = FALSE) %>%
  select(1:7, away.code=8) %>%
  merge(y = cap.dist, by.x = c("home.code", "away.code"), 
        by.y = c("ida", "idb"), all.x = TRUE, all.y = FALSE) 

for(i in 1:nrow(games)){
  if(is.na(games$kmdist[i])){
    games$kmdist[i] <- quantile(games$kmdist, rtriangle(a=0.1,b=0.9, c=0.3), na.rm = TRUE)
  }
}

games$home.win <- ifelse(games$home_score>games$away_score, 1, 0)
games$away.win <- ifelse(games$home_score<games$away_score, 1, 0)
games$both.draw <- ifelse(games$home_score==games$away_score, 1, 0)
games$home.team <- as.character(games$home_team)
games$away.team <- as.character(games$away_team)
games$home.code <- as.character(games$home.code)
games$away.code <- as.character(games$away.code)
games$bins <- cut(games$year, breaks = seq(1946,2018,by=4),include.lowest = FALSE, right = TRUE)
games$tourney.year <- as.numeric(str_sub(games$bins, -5, -2))

games.df <- data.frame(team = c(games$home.team, games$away.team), team.init = c(games$home.code, games$away.code), goals = c(games$home_score, games$away_score), goal.diff = c(games$home_score-games$away_score, games$away_score-games$home_score), win = c(games$home.win, games$away.win), draw = rep(games$both.draw, 2), distance.from.home = c(rep(0, nrow(games)),games$kmdist), year = rep(games$year,2))

games.df$bins <- cut(games.df$year, breaks = seq(1946,2018,by=4),include.lowest = FALSE, right = TRUE)
games.df$tourney.year <- as.numeric(str_sub(games.df$bins, -5, -2))

games.sum <- ddply(games.df, .(tourney.year, team), summarise, win.rate.home = sum(win[distance.from.home<=1500])/sum(distance.from.home<=1500), win.rate.away = sum(win[distance.from.home>1500])/sum(distance.from.home>1500), win.rate = sum(win)/n())


```



```{r}
wcup <- read.csv("WorldCupMatches.csv")
head(wcup[200:400,])
wcup$home.win <- ifelse(wcup$Home.Team.Goals > wcup$Away.Team.Goals,1,0)
wcup$away.win <- ifelse(wcup$Home.Team.Goals < wcup$Away.Team.Goals,1,0)
wcup$both.draw <- wcup$home.win <- ifelse(wcup$Home.Team.Goals==wcup$Away.Team.Goals,1,0)


w.cup2 <- data.frame(year = rep(wcup$Year, 2), 
                     stage = rep(wcup$Stage, 2), 
                     team = c(as.character(wcup$Home.Team.Name), as.character(wcup$Away.Team.Name)), 
                     team.init = c(as.character(wcup$Home.Team.Initials), 
                                   as.character(wcup$Away.Team.Initials)), 
                     goals = c(wcup$Home.Team.Goals, wcup$Away.Team.Goals), 
                     goal.diff = c(wcup$Home.Team.Goals - wcup$Away.Team.Goals,
                                   wcup$Away.Team.Goals - wcup$Home.Team.Goals),
                     win = c(ifelse(wcup$Home.Team.Goals > wcup$Away.Team.Goals,1,0), ifelse(wcup$Home.Team.Goals < wcup$Away.Team.Goals,1,0)), 
                     draw = rep(as.numeric(wcup$both.draw),2))
w.cup2 <- unique(w.cup2)

w.cup2 <- subset(w.cup2, year>=1950)

## Approach 1
fifa.outcomes <- ddply(w.cup2, .(year, team), summarise, 
      group.stage = ifelse(any(grepl(x = stage, pattern = "Group")),1,0),
      field16 = ifelse(nlevels(factor(stage))>1,1,0),
      final8 = ifelse(any(grepl(x=stage, pattern = "Quarter")) || 
                        sum(grepl(x=stage, pattern = "Group"))>4, 1,0),
      final4 = ifelse(any(grepl(x=stage, pattern  = "Semi")), 1,0),
      final.stage = ifelse(any(grepl(x = stage, pattern = "Final", ignore.case = FALSE)),1,0),
      fifa.champ = ifelse(any(grepl(x = stage, pattern = "Final", ignore.case = FALSE)) && win[stage=="Final"]==1,1,0), 
      n.games = length(stage))

fifa.outcomes$top.stage <- ifelse(fifa.outcomes$fifa.champ == 1,
                                  "fifa.champ",
                                  ifelse(fifa.outcomes$final.stage==1,
                                         "final2",
                                         ifelse(fifa.outcomes$final4==1,
                                                "final4",
                                                ifelse(fifa.outcomes$final8==1,
                                                       "final8",
                                                       ifelse(fifa.outcomes$field16==1,
                                                              "field16",
                                                              ifelse(fifa.outcomes$group.stage==1,
                                                                     "group.stage", "not.qualified")))))
  
)

fifa.outcomes$rolling.group <- rep(0, nrow(fifa.outcomes))
fifa.outcomes$rolling.16 <- rep(0, nrow(fifa.outcomes))
fifa.outcomes$rolling.8 <- rep(0, nrow(fifa.outcomes))
fifa.outcomes$rolling.4 <- rep(0, nrow(fifa.outcomes))
fifa.outcomes$rolling.2 <- rep(0, nrow(fifa.outcomes))
fifa.outcomes$rolling.champ <- rep(0, nrow(fifa.outcomes))
fifa.outcomes$rolling.games <- rep(0, nrow(fifa.outcomes))

for( i in 1:nrow(fifa.outcomes)){
  sub.i <- fifa.outcomes %>%
    subset(team == team[i] & year<year[i]) %>%
    select(3:9)
  fifa.outcomes$rolling.16[i] <- sum(sub.i$field16,na.rm = TRUE)
  fifa.outcomes$rolling.group[i] <- sum(sub.i$group.stage,na.rm = TRUE)
  fifa.outcomes$rolling.8[i] <- sum(sub.i$final8,na.rm = TRUE)
  fifa.outcomes$rolling.4[i] <- sum(sub.i$final4,na.rm = TRUE)
  fifa.outcomes$rolling.2[i] <- sum(sub.i$final.stage,na.rm = TRUE)
  fifa.outcomes$rolling.champ[i] <- sum(sub.i$fifa.champ,na.rm = TRUE)
  fifa.outcomes$rolling.games[i] <- sum(sub.i$n.games,na.rm = TRUE)
}



```

```{r}
fifa.outcomes$team <- as.character(fifa.outcomes$team)
fifa.outcomes$team[fifa.outcomes$team=="Germany FR"] <- "West Germany"
fifa.outcomes$team[fifa.outcomes$team=="German DR"] <- "East Germany"
fifa.outcomes$team[fifa.outcomes$team=="Korea DPR"] <- "North Korea"
fifa.outcomes$team[fifa.outcomes$team=="IR Iran"] <- "Iran"
fifa.outcomes$team[fifa.outcomes$team=="USA"] <- "United States"
fifa.outcomes$team[fifa.outcomes$team=="China PR"] <- "China"
fifa.outcomes$team[fifa.outcomes$team=="Korea Republic"] <- "South Korea"
fifa.outcomes$team[fifa.outcomes$team=='rn\">United Arab Emirates'] <- "United Arab Emirates"
fifa.outcomes$team[fifa.outcomes$team=="Czech Republic"] <- "Czechoslovakia"
fifa.outcomes$team[fifa.outcomes$team=='rn\">Republic of Ireland'] <- "Ireland"
fifa.outcomes$team[fifa.outcomes$team=="Cï¿½te d'Ivoire"] <- "Ivory Coast"
fifa.outcomes$team[fifa.outcomes$team=='rn\">Bosnia and Herzegovina'] <- "Bosnia and Herzegovina"
fifa.outcomes$team[fifa.outcomes$team=='rn\">Trinidad and Tobago'] <- "Trinidad and Tobago"
fifa.outcomes$team[fifa.outcomes$team=='rn\">Serbia and Montenegro'] <- "Serbia"


fifa.pred <- merge.data.frame(x = fifa.df2, y =fifa.outcomes, by.x = c("year", "country"), by.y = c("year", "team"), all.x = TRUE, all.y = FALSE)

fifa.pred$top.stage[is.na(fifa.pred$top.stage)] <- "not.qualified"
fifa.pred$top.stage[fifa.pred$year==2018] <- NA
fifa.pred <- subset(fifa.pred, is.na(top.stage) | top.stage != "not.qualified")
fifa.pred$top.stage <- factor(fifa.pred$top.stage, levels = c("not.qualified", "group.stage", "field16", "final8", "final4", "final2", "fifa.champ"))

```

```{r}
## additional feature engineering
fifa.pred$win.ratio <- fifa.pred$wins/fifa.pred$total.games
fifa.pred$draw.ratio <- fifa.pred$draws/fifa.pred$total.games
fifa.pred$loss.ratio <- fifa.pred$losses/fifa.pred$total.games
fifa.pred$home.ratio <- fifa.pred$home/fifa.pred$total.games
fifa.pred$away.ratio <- (fifa.pred$away+fifa.pred$neutral)/fifa.pred$total.games
fifa.pred$goals.per.game <- fifa.pred$goals.for/fifa.pred$total.games
fifa.pred$goalsAllowed.per.game <- fifa.pred$goals.against/fifa.pred$total.games
fifa.pred$rating.change.ratio <- 
  fifa.pred$year.change.rating / (fifa.pred$year.change.rating+fifa.pred$rating)
fifa.pred$rating.change.ratio[is.na(fifa.pred$rating.change.ratio)] <- 1 #hard coding NAs
```

```{r eval = FALSE, include = FALSE}
fifa.pred <- arrange(fifa.pred, year, rank)
for (i in 1:nrow(fifa.pred)) {
  if (fifa.pred$year[i]==2018){
    if (nrow(subset(fifa.pred, year < fifa.pred$year[i] & fifa.pred$country==fifa.pred$country[i]))==0){
       fifa.pred$rolling.group[i] <- 0
    fifa.pred$rolling.16[i] <- 0
    fifa.pred$rolling.8[i] <- 0
    fifa.pred$rolling.4[i] <- 0
    fifa.pred$rolling.2[i] <- 0
    fifa.pred$rolling.champ[i] <- 0
    fifa.pred$rolling.games[i] <- 0
    }
    else{
      sub.i <- subset(fifa.pred, year < fifa.pred$year[i] & fifa.pred$country==fifa.pred$country[i])
      sub.i <- subset(sub.i, year == max(year))
      if (sub.i$top.stage == "fifa.champ"){
        fifa.pred$rolling.group[i] <- sub.i$rolling.group + 1
        fifa.pred$rolling.16[i] <- sub.i$rolling.16 + 1
        fifa.pred$rolling.8[i] <- sub.i$rolling.8 + 1
        fifa.pred$rolling.4[i] <- sub.i$rolling.4 + 1
        fifa.pred$rolling.2[i] <- sub.i$rolling.2 + 1
        fifa.pred$rolling.champ[i] <- sub.i$rolling.champ + 1
        fifa.pred$rolling.games[i] <- sub.i$rolling.games + sub.i$n.games
      }
      else if (sub.i$top.stage == "final2"){
        fifa.pred$rolling.group[i] <- sub.i$rolling.group + 1
        fifa.pred$rolling.16[i] <- sub.i$rolling.16 + 1
        fifa.pred$rolling.8[i] <- sub.i$rolling.8 + 1
        fifa.pred$rolling.4[i] <- sub.i$rolling.4 + 1
        fifa.pred$rolling.2[i] <- sub.i$rolling.2 + 1
        fifa.pred$rolling.champ[i] <- sub.i$rolling.champ
        fifa.pred$rolling.games[i] <- sub.i$rolling.games + sub.i$n.games
      }
      else if (sub.i$top.stage == "final4"){
        fifa.pred$rolling.group[i] <- sub.i$rolling.group + 1
        fifa.pred$rolling.16[i] <- sub.i$rolling.16 + 1
        fifa.pred$rolling.8[i] <- sub.i$rolling.8 + 1
        fifa.pred$rolling.4[i] <- sub.i$rolling.4 + 1
        fifa.pred$rolling.2[i] <- sub.i$rolling.2
        fifa.pred$rolling.champ[i] <- sub.i$rolling.champ
        fifa.pred$rolling.games[i] <- sub.i$rolling.games + sub.i$n.games
      }
      else if (sub.i$top.stage == "final8"){
        fifa.pred$rolling.group[i] <- sub.i$rolling.group + 1
        fifa.pred$rolling.16[i] <- sub.i$rolling.16 + 1
        fifa.pred$rolling.8[i] <- sub.i$rolling.8 + 1
        fifa.pred$rolling.4[i] <- sub.i$rolling.4
        fifa.pred$rolling.2[i] <- sub.i$rolling.2
        fifa.pred$rolling.champ[i] <- sub.i$rolling.champ
        fifa.pred$rolling.games[i] <- sub.i$rolling.games + 7
      }
      else if (sub.i$top.stage == "field16"){
        fifa.pred$rolling.group[i] <- sub.i$rolling.group + 1
        fifa.pred$rolling.16[i] <- sub.i$rolling.16 + 1
        fifa.pred$rolling.8[i] <- sub.i$rolling.8
        fifa.pred$rolling.4[i] <- sub.i$rolling.4
        fifa.pred$rolling.2[i] <- sub.i$rolling.2
        fifa.pred$rolling.champ[i] <- sub.i$rolling.champ
        fifa.pred$rolling.games[i] <- sub.i$rolling.games + sub.i$n.games
      }
      else if (sub.i$top.stage == "group.stage"){
        fifa.pred$rolling.group[i] <- sub.i$rolling.group + 1
        fifa.pred$rolling.16[i] <- sub.i$rolling.16
        fifa.pred$rolling.8[i] <- sub.i$rolling.8
        fifa.pred$rolling.4[i] <- sub.i$rolling.4
        fifa.pred$rolling.2[i] <- sub.i$rolling.2
        fifa.pred$rolling.champ[i] <- sub.i$rolling.champ
        fifa.pred$rolling.games[i] <- sub.i$rolling.games + sub.i$n.games
      }
        
    }
  }
}

```

```{r}
## selection prediciton variables

fifa.df2018 <- fifa.pred %>%
  filter(year == 2018)

fifa.pred2 <- fifa.pred %>%
  select(1:4, 8:9, 26:41) %>%
  filter(year<2018)
fifa.pred2$top.stage <- factor(fifa.pred2$top.stage)
#levels(fifa.pred2$top.stage)

```

```{r}
library(e1071)
#library(libsvm)
library(rpart)
library(rpart.plot)

train.index <- sample(x = 1:nrow(fifa.pred2), size = round(nrow(fifa.pred2)*0.8, 0), replace = FALSE)

fifa.svm <- svm(top.stage ~ . - country - year, data = fifa.pred2[train.index,], probability = TRUE)
summary(fifa.svm)
svm.prediction <- predict(fifa.svm, fifa.pred2[train.index,], probability = TRUE)
head(attr(svm.prediction, "probabilities"))
table(svm.prediction,fifa.pred2[train.index,"top.stage"])
sum(svm.prediction==fifa.pred2[train.index,"top.stage"])/length(svm.prediction)

svm.pred.test <- predict(fifa.svm, fifa.pred2[-train.index,], probability = TRUE)
table(svm.pred.test,fifa.pred2[-train.index,"top.stage"])
sum(svm.pred.test==fifa.pred2[-train.index,"top.stage"])/length(svm.pred.test)
#attr(svm.prediction, "probabilities")

#fifa.tree <- rpart(top.stage ~ year + rating + year.change.rating + goals.for + goals.against + wins + losses + draws, data = fifa.pred)

plot.svm(fifa.svm)
```

```{r}
## Tuning SVM
fifa.x <- select(fifa.pred2, -country, -year, - top.stage)
fifa.y <- select(fifa.pred2, top.stage)
fifa.tune <- tune.svm(top.stage~.-country-year, data = fifa.pred2[train.index,], gamma = 10^(-6:-3), cost = 10^(1:6))

summary(fifa.tune)
fifa.tuned.svm <- svm(top.stage ~ . - country - year, data = fifa.pred2[train.index,], probability = TRUE, gamma = 0.0001, cost = 10000)

pred.tuned <- predict(fifa.tuned.svm, fifa.pred2[train.index,], probability = TRUE)
table(pred.tuned,fifa.pred2[train.index,"top.stage"])
sum(pred.tuned==fifa.pred2[train.index,"top.stage"])/length(pred.tuned)

tuned.test <- predict(fifa.tuned.svm, fifa.pred2[-train.index,], probability = TRUE)
table(tuned.test,fifa.pred2[-train.index,"top.stage"])
sum(tuned.test==fifa.pred2[-train.index,"top.stage"])/length(tuned.test)
#attr(tuned.test, "probabilities")
```


```{r}
## 2018 predictions
teams2018 <- c("Egypt","Morocco","Nigeria","Senegal","Tunisia","Australia","Iran","Japan",
               "South Korea","Saudi Arabia", "Belgium", "Croatia","Denmark","England",
               "France","Germany", "Iceland", "Poland","Portugal","Russia","Serbia",
               "Spain", "Sweden","Switzerland","Costa Rica","Mexico","Panama","Argentina", 
               "Brazil","Colombia","Peru","Uruguay")
groups2018 <- subset(fifa.df2018, country %in% teams2018) %>%
  select(1:17,27:41)
fifa2018.svm <- predict(fifa.tuned.svm, groups2018, probability = TRUE)
table(fifa2018.svm)
#data.frame(attr(fifa2018.svm, "probabilities"))

groups2018.results <- cbind.data.frame(groups2018, data.frame(attr(fifa2018.svm, "probabilities")))

groups2018.results[groups2018.results$fifa.champ>quantile(groups2018.results$fifa.champ,0.9),]

groups2018.results$adj2 <- groups2018.results$final2 + groups2018.results$fifa.champ
groups2018.results$adj4 <- groups2018.results$final4 + groups2018.results$adj2
groups2018.results$adj8 <- groups2018.results$final8 + groups2018.results$adj4
groups2018.results$adj16 <- groups2018.results$field16 + groups2018.results$adj8
groups2018.results$adj.group <- groups2018.results$group.stage + groups2018.results$adj16
groups2018.results$majority.prediction <- as.character(fifa2018.svm)

arrange(select(groups2018.results, country, rating, 36, 39:44), desc(fifa.champ))
```

```{r fig.height=12, fig.width=12}
rpart.plot(fifa.tree)
```

```{r}
## random forest?
library(randomForest)

fifa.rf <- randomForest(top.stage ~ . - country - year, data = fifa.pred2[train.index,])
summary(fifa.rf)
rf.prediction <- predict(fifa.rf, fifa.pred2[train.index,])
#head(attr(svm.prediction, "probabilities"))
table(rf.prediction,fifa.pred2[train.index,"top.stage"])
sum(rf.prediction==fifa.pred2[train.index,"top.stage"])/length(rf.prediction)

rf.pred.test <- predict(fifa.rf, fifa.pred2[-train.index,])
rf.pred.test.probs <- predict(fifa.rf, fifa.pred2[-train.index,], type = "prob")
table(rf.pred.test,fifa.pred2[-train.index,"top.stage"])
sum(rf.pred.test==fifa.pred2[-train.index,"top.stage"])/length(rf.pred.test)
#attr(svm.prediction, "probabilities")

head(rf.pred.test)

## rf tuning

rf.tune <- tuneRF(y = fifa.y[train.index,], x = fifa.x[train.index,])
rf.tune2 <- tune.randomForest(y = fifa.y[train.index,], x = fifa.x[train.index,], mtry = 5, nodesize = 6:7, ntree = 70:71)


## tuned rf model:

fifa.rf2 <- randomForest(top.stage ~ . - country - year, data = fifa.pred2[train.index,], nodesize = 7, mtry = 5, ntree = 70)
rf.pred2 <- predict(fifa.rf2, fifa.pred2[train.index,])
table(rf.pred2,fifa.pred2[train.index,"top.stage"])
sum(rf.pred2==fifa.pred2[train.index,"top.stage"])/length(rf.pred2)

rf.test2 <- predict(fifa.rf2, fifa.pred2[-train.index,])
rf.probs2 <- predict(fifa.rf2, fifa.pred2[-train.index,], type = "prob")
table(rf.test2,fifa.pred2[-train.index,"top.stage"])
sum(rf.test2==fifa.pred2[-train.index,"top.stage"])/length(rf.test2)
```

```{r}
## 2018 predictions
teams2018 <- c("Egypt","Morocco","Nigeria","Senegal","Tunisia","Australia","Iran","Japan",
               "South Korea","Saudi Arabia", "Belgium", "Croatia","Denmark","England",
               "France","Germany", "Iceland", "Poland","Portugal","Russia","Serbia",
               "Spain", "Sweden","Switzerland","Costa Rica","Mexico","Panama","Argentina", 
               "Brazil","Colombia","Peru","Uruguay")
groups2018 <- subset(fifa.df2018, country %in% teams2018) %>%
  select(1:17,27:41)
fifa2018.rf <- predict(fifa.rf2, groups2018, type = "prob")
table(fifa2018.rf)
#data.frame(attr(fifa2018.svm, "probabilities"))

rf2018 <- cbind.data.frame(groups2018, fifa2018.rf)

rf2018[rf2018$fifa.champ>quantile(rf2018$fifa.champ,0.9),]

rf2018$adj2 <- rf2018$final2 + rf2018$fifa.champ
rf2018$adj4 <- rf2018$final4 + rf2018$adj2
rf2018$adj8 <- rf2018$final8 + rf2018$adj4
rf2018$adj16 <- rf2018$field16 + rf2018$adj8
rf2018$adj.group <- rf2018$group.stage + rf2018$adj16
rf2018$majority.prediction <- predict(fifa.rf2, groups2018)

arrange(select(rf2018, country, rating, 36, 37:43), desc(fifa.champ))
```

```{r eval = FALSE}
fifa.seq <- fifa.pred %>%
  select(1:4, 8:9, 26:41, 19:24) %>%
  filter(year<2018)
fifa.seq$top.stage <- factor(fifa.seq$top.stage)
fifa.seq$field16 <- as.factor(fifa.seq$field16)
fifa.seq$year <- as.numeric(as.character(fifa.seq$year))

names(fifa.seq)
for (i in 3:5){
  train.index <- sample(x = 1:nrow(fifa.seq), size = round(nrow(fifa.seq)*0.8, 0), replace = FALSE)
  
  field16.tuned <- tune.randomForest(x = fifa.seq[train.index,3:22], y = fifa.seq[train.index,"field16"], mtry = i, nodesize = 5:7, ntree = 70:75)$best.model
  
  field16.pred <- predict(field16.tuned, fifa.seq[train.index,], type = "prob")
  
  fifa.seq2 <- fifa.seq[train.index,] %>%
    mutate(field16.probs = field16.pred[,2]) %>%
    group_by(year) %>%
    mutate(field16.rank = rank(field16.probs, ties.method = "random")) %>%
    filter(field16.rank<=16) %>%
    ungroup()
  
  for (j in 3:5){
    train.index <- sample(x = 1:nrow(fifa.seq2), size = round(nrow(fifa.seq2)*0.8, 0), replace = FALSE)
    
    field8.tuned <- tune.randomForest(
      x = fifa.seq2[train.index,c(3:22, ncol(fifa.seq2)-1:ncol(fifa.seq2))], 
      y = fifa.seq2[train.index,"final8"], 
      mtry = j, nodesize = 5:7, ntree = 70:75)$best.model
    
    field8.pred <- predict(field8.tuned, fifa.seq2[train.index,], type = "prob")
    
    fifa.seq3 <- fifa.seq2[train.index,] %>%
      mutate(field8.probs = field8.pred[,2]) %>%
      group_by(year) %>%
      mutate(field8.rank = rank(field8.probs, ties.method = "random")) %>%
      filter(field8.rank<=8) %>%
      ungroup()
    
    for (k in 3:5){
      train.index <- sample(x = 1:nrow(fifa.seq3), size = round(nrow(fifa.seq3)*0.8, 0), replace = FALSE)
    
      field4.tuned <- tune.randomForest(
        x = fifa.seq3[train.index,c(3:22, ncol(fifa.seq3)-3:ncol(fifa.seq3))], 
        y = fifa.seq3[train.index,"field4"], 
        mtry = k, nodesize = 5:7, ntree = 70:75)$best.model
    
      field4.pred <- predict(field8.tuned, fifa.seq3[train.index,], type = "prob")
      
      fifa.seq4 <- fifa.seq3[train.index,] %>%
        mutate(field4.probs = field4.pred[,2]) %>%
        group_by(year) %>%
        mutate(field4.rank = rank(field4.probs, ties.method = "random")) %>%
        filter(field4.rank<=4) %>%
        ungroup()
      for (l in 3:5){
        train.index <- sample(x = 1:nrow(fifa.seq4), size = round(nrow(fifa.seq4)*0.8, 0), replace = FALSE)
    
        field2.tuned <- tune.randomForest(
          x = fifa.seq4[train.index,c(3:22, ncol(fifa.seq4)-5:ncol(fifa.seq4))], 
          y = fifa.seq4[train.index,"final2"], 
          mtry = l, nodesize = 5:7, ntree = 70:75)$best.model
      
        field2.pred <- predict(field2.tuned, fifa.seq4[train.index,], type = "prob")
        
        fifa.seq5 <- fifa.seq4[train.index,] %>%
          mutate(field2.probs = field2.pred[,2]) %>%
          group_by(year) %>%
          mutate(field2.rank = rank(field2.probs, ties.method = "random")) %>%
          filter(field2.rank<=2) %>%
          ungroup()
        
        for (m in 3:5){
          train.index <- sample(x = 1:nrow(fifa.seq5), size = round(nrow(fifa.seq5)*0.8, 0), replace = FALSE)
    
          final.tuned <- tune.randomForest(
            x = fifa.seq5[train.index,c(3:22, ncol(fifa.seq5)-7:ncol(fifa.seq5))], 
            y = fifa.seq5[train.index,"fifa.champ"], 
            mtry = m, nodesize = 5:7, ntree = 70:75)$best.model
        
          final.pred <- predict(field2.tuned, fifa.seq5[train.index,], type = "prob")
          
          fifa.seq6 <- fifa.seq5[train.index,] %>%
            mutate(final.probs = final.pred[,2]) %>%
            group_by(year) %>%
            mutate(field2.rank = rank(final.probs, ties.method = "random")) %>%
            filter(field2.rank<=1) %>%
            ungroup()
          
          summary(final.tuned)
          summary(field2.tuned)
          summary(field4.tuned)
          summary(field8.tuned)
          summary(field16.tuned)
          
          
        }
      
      }
    }
  
    
  }
    
  
}
  
```




```{r}
write.csv(file = "fifaPredictionData.csv", fifa.pred2)
write.csv(file = "randomForestResults.csv", rf2018)
write.csv(file = "svmResults.csv", groups2018.results)

```

```{r}
fifa.formatted <- mutate(fifa.pred2, country2 = paste(country, year, sep = ", ")) %>%
  select(3:6, 15:17, 20:21, 23)

names(fifa.formatted) <- c("World Rank", "ELO Rating", "Yearly Change in ELO", "Total Games Played", "Win Ratio", "Lose Ratio", "Draw Ratio", "Mean Goals Scored per Game", "Mean Goals Allowed per Game", "Nation")

fifa.formatted <- select(fifa.formatted, "Nation", 1:(ncol(fifa.formatted)-1))

write.csv(file = "fifaFormat.csv", fifa.formatted)

```

```{r}
heat2018 <- fifa.df2018 %>%
  select(2, 27:32) %>%
  filter(country %in% teams2018)

heat1978 <- fifa.pred %>%
  select(1,2,27:33) %>%
  filter(country %in% teams2018) %>%
  filter(year == 1978) %>%
  unique()

not.in1978 <- teams2018[!c(teams2018 %in% heat1978$country)]
not1978 <- cbind(data.frame(year = rep(1978, length(not.in1978)), country = not.in1978), data.frame(matrix(rep(0, 7*length(not.in1978)), ncol = 7)))
names(not1978) <- names(heat1978)
heat1978 <- rbind.data.frame(heat1978, not1978) %>%
  select(2:8)
names(heat1978) <- c("Country", "World Cup Appearances", "Field of 16 Appearances", "Quarterfinal Appearances", "Semifianl Appearances", "Final Appearances", "World Cup Champions")

heat1998 <- fifa.pred %>%
  select(1,2,27:33) %>%
  filter(country %in% teams2018) %>%
  filter(year == 1998) %>%
  unique()

not.in1998 <- teams2018[!c(teams2018 %in% heat1998$country)]

not1998 <- cbind(data.frame(year = 1998, country = not.in1998), data.frame(matrix(rep(0, 7*length(not.in1998)), ncol = 7)))
names(not1998) <- names(heat1998)
heat1998 <- rbind.data.frame(heat1998, not1998) %>%
  select(2:8)

names(heat1998) <- c("Country", "World Cup Appearances", "Field of 16 Appearances", "Quarterfinal Appearances", "Semifianl Appearances", "Final Appearances", "World Cup Champions")
names(heat2018) <- c("Country", "World Cup Appearances", "Field of 16 Appearances", "Quarterfinal Appearances", "Semifianl Appearances", "Final Appearances", "World Cup Champions")

heat1978adj <- heat1978 %>%
  melt.data.frame(id.vars = 1, variable_name = "stage") %>%
  arrange(Country)

heat1978adj$Country <- factor(heat1978adj$Country)
heat1978adj$Country <- factor(heat1978adj$Country, levels = sort(levels(heat1978adj$Country)))
heat1978adj$Country <- mapvalues(heat1978adj$Country, from = levels(heat1978adj$Country), to = 1:32)
heat1978adj$stage <- mapvalues(heat1978adj$stage, from = levels(heat1978adj$stage), to = 1:6)



heat1998adj <- heat1998 %>%
  melt.data.frame(id.vars = 1, variable_name = "stage") %>%
  arrange(Country)

heat1998adj$Country <- factor(heat1998adj$Country)
heat1998adj$Country <- factor(heat1998adj$Country, levels = sort(levels(heat1998adj$Country)))
heat1998adj$Country <- mapvalues(heat1998adj$Country, from = levels(heat1998adj$Country), to = 1:32)
heat1998adj$stage <- mapvalues(heat1998adj$stage, from = levels(heat1998adj$stage), to = 1:6) 
 
heat2018adj <- heat2018 %>%
  melt.data.frame(id.vars = 1, variable_name = "stage") %>%
  arrange(Country)

heat2018adj$Country <- factor(heat2018adj$Country)
heat2018adj$Country <- factor(heat2018adj$Country, levels = sort(levels(heat2018adj$Country)))
heat2018adj$Country <- mapvalues(heat2018adj$Country, from = levels(heat2018adj$Country), to = 1:32)
heat2018adj$stage <- mapvalues(heat2018adj$stage, from = levels(heat2018adj$stage), to = 1:6)

write.table(heat1978adj, file='heat1978.tsv', quote=FALSE, sep='\t', col.names = NA)
write.table(heat1998adj, file='heat1998.tsv', quote=FALSE, sep='\t', col.names = NA)
write.table(heat2018adj, file='heat2018.tsv', quote=FALSE, sep='\t', col.names = NA)


```
